### ISSUE TITLE
fatal error C1083: Cannot open include file: 'io.h': No such file or directory

### ISSUE THREAD

**Issue by jbflow** [ztane/python-Levenshtein#67]
I'm having trouble installing on Python 3.9.2, in a venv. Pretty sure the following error is the culprit. 
`fatal error C1083: Cannot open include file: 'io.h': No such file or directory`

Had this working on Python 3.8 no problem but now no longer working since updating. I've created a new venv and reinstalled everything but getting this issue.

**Comment by alex-d13** [comment]
Same problem here, did you solve it?
